import {
  DanafixIcon,
  DanafixScreen1,
  DanafixScreen2,
  DanafixScreen3,
  DanafixScreen4,
  DanafixScreen5,
  DanafixScreen6,
  DanafixScreen7,
  IzilohIcon,
  IzilohScreen1,
  IzilohScreen2,
  IzilohScreen3,
  IzilohScreen4,
  IzilohScreen5,
  IzilohScreen6,
  IzilohScreen7,
  IzilohScreen8,
  TribelioIcon,
  TribelioScreen1,
  TribelioScreen2,
  TribelioScreen3,
  TribelioScreen4,
  TribelioScreen5,
  TribelioScreen6,
  TribelioScreen7,
  WRIcon,
  WRScreen1,
  WRScreen2,
  WRScreen3,
  WRScreen4,
  WRScreen5,
  WRScreen6,
  WRScreen7,
  WRScreen8,
} from "../assets";

export const ProjectList = [
  {
    name: "Waroong Retjeh",
    image: WRIcon,
    company: "PT. Ittron Global Teknologi",
    preview: [
      WRScreen1,
      WRScreen2,
      WRScreen3,
      WRScreen4,
      WRScreen5,
      WRScreen6,
      WRScreen7,
      WRScreen8,
    ],
    skills: "Flutter, Firebase(Messaging, Deeplink & Crashlytics), Google Maps, Shared Preference, Gitlab",
    android: "https://play.google.com/store/apps/details?id=com.waroongretjeh",
    ios: "https://apps.apple.com/id/app/id1500756520"
  },
  {
    name: "Iziloh",
    image: IzilohIcon,
    company: "PT. Ittron Global Teknologi",
    preview: [
      IzilohScreen1,
      IzilohScreen2,
      IzilohScreen3,
      IzilohScreen4,
      IzilohScreen5,
      IzilohScreen6,
      IzilohScreen7,
      IzilohScreen8,
    ],
    skills: "Flutter, Firebase(Messaging, Deeplink & Crashlytics), Google Maps, XMPP, Shared Preference, Blue Thermal Print",
    android: "https://play.google.com/store/search?q=iziloh&c=apps",
    ios: "https://apps.apple.com/id/app/iziloh/id1540527254"
  },
  {
    name: "Tribelio",
    image: TribelioIcon,
    company: "PT. Ittron Global Teknologi",
    preview: [
      TribelioScreen1,
      TribelioScreen2,
      TribelioScreen3,
      TribelioScreen4,
      TribelioScreen5,
      TribelioScreen6,
      TribelioScreen7,
    ],
    skills: "Flutter, Firebase(Messaging, Deeplink & Crashlytics), Google Maps, Qisqus, Shared Preference",
    android: "https://play.google.com/store/apps/details?id=com.app.tribelio",
    ios: "https://apps.apple.com/id/app/tribelio/id1478705376"
  },
  {
    name: "Danafix",
    image: DanafixIcon,
    company: "PT. Danafix Online Indonesia",
    preview: [
      DanafixScreen1,
      DanafixScreen2,
      DanafixScreen3,
      DanafixScreen4,
      DanafixScreen5,
      DanafixScreen6,
      DanafixScreen7,
    ],
    skills: "Flutter, Firebase(Analytics, Crashlytics), Geolocator, Shared Preference, Bloc, Appsflyer, Clean Architecture, Dependency Injection(Get It)",
    android: "https://play.google.com/store/apps/details?id=id.danafix.mobile",
    ios: "https://apps.apple.com/id/app/danafix-pinjaman-online-uang/id1572941962?l=id"
  },
];
